//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.586
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.JackJCSN.DataAPI {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class R {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal R() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.JackJCSN.DataAPI.R", typeof(R).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 连接 的本地化字符串。
        /// </summary>
        public static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已连接 的本地化字符串。
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接 的本地化字符串。
        /// </summary>
        public static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [ERROR]{1}:{0} 的本地化字符串。
        /// </summary>
        public static string Error_Format {
            get {
                return ResourceManager.GetString("Error_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [错误]
        ///{0}
        ///[解决]
        ///如果持续出现此错误，请联系程序作者
        ///[操作]
        ///{1} 的本地化字符串。
        /// </summary>
        public static string ErrorMsg_Format {
            get {
                return ResourceManager.GetString("ErrorMsg_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [INFO]{1}:{0} 的本地化字符串。
        /// </summary>
        public static string Info_Fomat {
            get {
                return ResourceManager.GetString("Info_Fomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内部错误 的本地化字符串。
        /// </summary>
        public static string InnerError {
            get {
                return ResourceManager.GetString("InnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未连接 的本地化字符串。
        /// </summary>
        public static string NotConnected {
            get {
                return ResourceManager.GetString("NotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [NOTICE]{1}:{0} 的本地化字符串。
        /// </summary>
        public static string Notice_Fomat {
            get {
                return ResourceManager.GetString("Notice_Fomat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管脚改变 的本地化字符串。
        /// </summary>
        public static string PinChanged {
            get {
                return ResourceManager.GetString("PinChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否停止运行程序? 的本地化字符串。
        /// </summary>
        public static string StopApplication {
            get {
                return ResourceManager.GetString("StopApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [WARRING]{1}:{0} 的本地化字符串。
        /// </summary>
        public static string Warring_Format {
            get {
                return ResourceManager.GetString("Warring_Format", resourceCulture);
            }
        }
    }
}
